---
language: java
script:
  - make && make test
  - make docker_image

jdk:
  - oraclejdk8

branches:
  only:
  - master
  - staging
  - develop

after_success:
  - IMAGE_NAME=kbase/kb_nms ./build/push2dockerhub.sh

